<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <BaseOutputPath>..\bin\</BaseOutputPath>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;Editor_d</Configurations>
  </PropertyGroup>

 <PropertyGroup>
  <TargetFramework>net8.0-windows</TargetFramework>
  <Nullable>enable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>
  <OutputPath>..\bin\$(Configuration)\</OutputPath>
  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
</PropertyGroup>

 <ItemGroup>
   <None Remove="Tool\EditorLuaWindow\Lua.xshd" />
   <None Remove="Tool\LuaDark.xshd" />
 </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.72.1" />
    <PackageReference Include="Microsoft.VisualStudio.LanguageServer.Protocol" Version="17.2.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="StreamJsonRpc" Version="2.24.84" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixelEngine\PixelEngine.vcxproj" />
    <ProjectReference Include="..\PixelGraphics\PixelGraphics.vcxproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Tool\EditorLuaWindow\Lua.xshd" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(ProjectDir)LSP\*.*&quot; &quot;$(TargetDir)LSP\&quot; /S /E /Y /I" />
  </Target>

</Project>
