/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040401
#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NOEXCEPT throw()
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_PixelEngine(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_PixelEngine(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_PixelEngine(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif

#if defined(__cplusplus) && (__cplusplus >=201103L)
# define SWIG_OVERRIDE override
#else
# define SWIG_OVERRIDE
#endif



/* 생성된 래퍼 파일에 포함될 헤더들 */
#include <windows.h>
#include "Export/PixelEngineAPI.h"
/* Type */
#include "Export/Type/PVector3.h"
#include "Export/Type/PMatrix.h"
#include "Export/Type/GlobalEnum.h"

/* GameObject */
#include "Export/Core/PixelObject.h"
#include "Export/Core/Module.h"
#include "Export/Core/GameObject.h"

/* Module */
#include "Export/Module/Camera.h"
#include "Export/Module/DebugCamera.h"
#include "Export/Module/Transform.h"
#include "Export/Module/LuaScript.h"
#include "Export/Module/Renderer2D.h"


#include <string>


typedef void (__stdcall * LogCallbackFunc)(const char *message, int level);

SWIGINTERN Camera *Camera_SafeCast(Module *baseModule){ 
            return dynamic_cast<Camera*>(baseModule); 
        }
SWIGINTERN DebugCamera *DebugCamera_SafeCast(Module *baseModule){ 
            return dynamic_cast<DebugCamera*>(baseModule); 
        }
SWIGINTERN Transform *Transform_SafeCast(Module *baseModule){ 
            return dynamic_cast<Transform*>(baseModule); 
        }
SWIGINTERN LuaScript *LuaScript_SafeCast(Module *baseModule){ 
            return dynamic_cast<LuaScript*>(baseModule); 
        }
SWIGINTERN Renderer2D *Renderer2D_SafeCast(Module *baseModule){ 
            return dynamic_cast<Renderer2D*>(baseModule); 
        }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_LogCallback_get() {
  void * jresult ;
  LogCallbackFunc result;
  
  result = (LogCallbackFunc)(0);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_EngineInitialize(void * jarg1, int jarg2, int jarg3) {
  unsigned int jresult ;
  HWND arg1 ;
  int arg2 ;
  int arg3 ;
  bool result;
  
  arg1 = (HWND)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (bool)EngineInitialize(SWIG_STD_MOVE(arg1),arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_UpdateEngine() {
  UpdateEngine();
}


SWIGEXPORT void SWIGSTDCALL CSharp_ReleaseEngine() {
  ReleaseEngine();
}


SWIGEXPORT void SWIGSTDCALL CSharp_QuitWindow() {
  QuitWindow();
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ResizeEngine(int jarg1, int jarg2) {
  unsigned int jresult ;
  int arg1 ;
  int arg2 ;
  bool result;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (bool)ResizeEngine(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_GetKeyDown(char jarg1) {
  unsigned int jresult ;
  char arg1 ;
  bool result;
  
  arg1 = (char)jarg1; 
  result = (bool)GetKeyDown(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_GetKeyUp(char jarg1) {
  unsigned int jresult ;
  char arg1 ;
  bool result;
  
  arg1 = (char)jarg1; 
  result = (bool)GetKeyUp(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_GetKey(char jarg1) {
  unsigned int jresult ;
  char arg1 ;
  bool result;
  
  arg1 = (char)jarg1; 
  result = (bool)GetKey(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GetMousePosition_X() {
  int jresult ;
  int result;
  
  result = (int)GetMousePosition_X();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GetMousePosition_Y() {
  int jresult ;
  int result;
  
  result = (int)GetMousePosition_Y();
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_GetDeltaTime() {
  float jresult ;
  float result;
  
  result = (float)GetDeltaTime();
  jresult = result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_GetTotalTime() {
  double jresult ;
  double result;
  
  result = (double)GetTotalTime();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GetFPS() {
  int jresult ;
  int result;
  
  result = (int)GetFPS();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_LoadLuaFile(char * jarg1) {
  unsigned int jresult ;
  char *arg1 = 0 ;
  bool result;
  
  arg1 = (char *)jarg1; 
  result = (bool)LoadLuaFile((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_LoadTexture(char * jarg1) {
  unsigned int jresult ;
  char *arg1 = 0 ;
  bool result;
  
  arg1 = (char *)jarg1; 
  result = (bool)LoadTexture((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_CreateLuaAPIPath(char * jarg1) {
  unsigned int jresult ;
  char *arg1 = 0 ;
  bool result;
  
  arg1 = (char *)jarg1; 
  result = (bool)CreateLuaAPIPath((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_CreateGameObject(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *)"" ;
  GameObject *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (GameObject *)CreateGameObject((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_CreateScene(char * jarg1) {
  unsigned int jresult ;
  char *arg1 = 0 ;
  bool result;
  
  arg1 = (char *)jarg1; 
  result = (bool)CreateScene((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ChangeScene(char * jarg1) {
  unsigned int jresult ;
  char *arg1 = 0 ;
  bool result;
  
  arg1 = (char *)jarg1; 
  result = (bool)ChangeScene((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SaveScene() {
  SaveScene();
}


SWIGEXPORT void SWIGSTDCALL CSharp_RegisterLogCallback(void * jarg1) {
  LogCallbackFunc arg1 = 0 ;
  
  arg1 = (LogCallbackFunc)jarg1; 
  RegisterLogCallback(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DispatchNativeLog(char * jarg1, int jarg2) {
  char *arg1 = 0 ;
  int arg2 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (int)jarg2; 
  DispatchNativeLog((char const *)arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PVector3__SWIG_0() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)new PVector3();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PVector3__SWIG_1(float jarg1, float jarg2, float jarg3) {
  void * jresult ;
  float *arg1 = 0 ;
  float *arg2 = 0 ;
  float *arg3 = 0 ;
  float temp1 ;
  float temp2 ;
  float temp3 ;
  PVector3 *result = 0 ;
  
  temp1 = (float)jarg1; 
  arg1 = &temp1; 
  temp2 = (float)jarg2; 
  arg2 = &temp2; 
  temp3 = (float)jarg3; 
  arg3 = &temp3; 
  result = (PVector3 *)new PVector3((float const &)*arg1,(float const &)*arg2,(float const &)*arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_PVector3_Dot__SWIG_0(void * jarg1, void * jarg2) {
  float jresult ;
  PVector3 *arg1 = 0 ;
  PVector3 arg2 ;
  PVector3 const *argp2 ;
  float result;
  
  arg1 = (PVector3 *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  argp2 = (PVector3 *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null PVector3 const", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (float)PVector3::Dot((PVector3 const &)*arg1,SWIG_STD_MOVE(arg2));
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Cross__SWIG_0(void * jarg1, void * jarg2) {
  void * jresult ;
  PVector3 *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  PVector3 result;
  
  arg1 = (PVector3 *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  result = PVector3::Cross((PVector3 const &)*arg1,(PVector3 const &)*arg2);
  jresult = new PVector3(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Normalize__SWIG_0(void * jarg1) {
  void * jresult ;
  PVector3 *arg1 = 0 ;
  PVector3 result;
  
  arg1 = (PVector3 *)jarg1; 
  result = (arg1)->Normalize();
  jresult = new PVector3(result); 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_PVector3_Distance__SWIG_0(void * jarg1, void * jarg2) {
  float jresult ;
  PVector3 *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  float result;
  
  arg1 = (PVector3 *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  result = (float)PVector3::Distance((PVector3 const &)*arg1,(PVector3 const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_PVector3_Distance__SWIG_1(void * jarg1) {
  float jresult ;
  PVector3 *arg1 = 0 ;
  float result;
  
  arg1 = (PVector3 *)jarg1; 
  result = (float)(arg1)->Distance();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Lerp(void * jarg1, void * jarg2, float jarg3) {
  void * jresult ;
  PVector3 *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  float arg3 ;
  PVector3 result;
  
  arg1 = (PVector3 *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  arg3 = (float)jarg3; 
  result = PVector3::Lerp((PVector3 const &)*arg1,(PVector3 const &)*arg2,arg3);
  jresult = new PVector3(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Zero_get() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)&PVector3::Zero;
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_One_get() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)&PVector3::One;
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Up_get() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)&PVector3::Up;
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Down_get() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)&PVector3::Down;
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Right_get() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)&PVector3::Right;
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Left_get() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)&PVector3::Left;
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Front_get() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)&PVector3::Front;
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PVector3_Back_get() {
  void * jresult ;
  PVector3 *result = 0 ;
  
  result = (PVector3 *)&PVector3::Back;
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PVector3_X_set(void * jarg1, float jarg2) {
  PVector3 *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (PVector3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->X = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_PVector3_X_get(void * jarg1) {
  float jresult ;
  PVector3 *arg1 = 0 ;
  float result;
  
  arg1 = (PVector3 *)jarg1; 
  result = (float) ((arg1)->X);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PVector3_Y_set(void * jarg1, float jarg2) {
  PVector3 *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (PVector3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->Y = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_PVector3_Y_get(void * jarg1) {
  float jresult ;
  PVector3 *arg1 = 0 ;
  float result;
  
  arg1 = (PVector3 *)jarg1; 
  result = (float) ((arg1)->Y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PVector3_Z_set(void * jarg1, float jarg2) {
  PVector3 *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (PVector3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->Z = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_PVector3_Z_get(void * jarg1) {
  float jresult ;
  PVector3 *arg1 = 0 ;
  float result;
  
  arg1 = (PVector3 *)jarg1; 
  result = (float) ((arg1)->Z);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PVector3(void * jarg1) {
  PVector3 *arg1 = 0 ;
  
  arg1 = (PVector3 *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PMatrix() {
  void * jresult ;
  PMatrix *result = 0 ;
  
  result = (PMatrix *)new PMatrix();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PMatrix(void * jarg1) {
  PMatrix *arg1 = 0 ;
  
  arg1 = (PMatrix *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PMatrix_Identity() {
  void * jresult ;
  PMatrix result;
  
  result = PMatrix::Identity();
  jresult = new PMatrix(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PMatrix_CreateTranslation(void * jarg1) {
  void * jresult ;
  PVector3 *arg1 = 0 ;
  PMatrix result;
  
  arg1 = (PVector3 *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  result = PMatrix::CreateTranslation((PVector3 const &)*arg1);
  jresult = new PMatrix(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PMatrix_CreateScale(void * jarg1) {
  void * jresult ;
  PVector3 *arg1 = 0 ;
  PMatrix result;
  
  arg1 = (PVector3 *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return 0;
  } 
  result = PMatrix::CreateScale((PVector3 const &)*arg1);
  jresult = new PMatrix(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PMatrix_CreateRotationRoll(float jarg1) {
  void * jresult ;
  float arg1 ;
  PMatrix result;
  
  arg1 = (float)jarg1; 
  result = PMatrix::CreateRotationRoll(arg1);
  jresult = new PMatrix(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PMatrix_CreateRotationPitch(float jarg1) {
  void * jresult ;
  float arg1 ;
  PMatrix result;
  
  arg1 = (float)jarg1; 
  result = PMatrix::CreateRotationPitch(arg1);
  jresult = new PMatrix(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PMatrix_CreateRotationYaw(float jarg1) {
  void * jresult ;
  float arg1 ;
  PMatrix result;
  
  arg1 = (float)jarg1; 
  result = PMatrix::CreateRotationYaw(arg1);
  jresult = new PMatrix(result); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_PMatrix_Invert(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  PMatrix *arg1 = 0 ;
  PMatrix *arg2 = 0 ;
  bool result;
  
  arg1 = (PMatrix *)jarg1; 
  arg2 = (PMatrix *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PMatrix & is null", 0);
    return 0;
  } 
  result = (bool)(arg1)->Invert(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PMatrix__m_set(void * jarg1, void * jarg2) {
  PMatrix *arg1 = 0 ;
  float *arg2 = (float *)0 ;
  
  arg1 = (PMatrix *)jarg1; 
  arg2 = (float *)jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->_m;
    for (ii = 0; ii < (size_t)16; ii++) b[ii] = *((float *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PMatrix__m_get(void * jarg1) {
  void * jresult ;
  PMatrix *arg1 = 0 ;
  float *result = 0 ;
  
  arg1 = (PMatrix *)jarg1; 
  result = (float *)(float *) ((arg1)->_m);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PixelObject() {
  void * jresult ;
  PixelObject *result = 0 ;
  
  result = (PixelObject *)new PixelObject();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PixelObject(void * jarg1) {
  PixelObject *arg1 = 0 ;
  
  arg1 = (PixelObject *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PixelObject_cBlock_set(void * jarg1, void * jarg2) {
  PixelObject *arg1 = 0 ;
  PtrControlBlock *arg2 = 0 ;
  
  arg1 = (PixelObject *)jarg1; 
  arg2 = (PtrControlBlock *)jarg2; 
  if (arg1) (arg1)->cBlock = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PixelObject_cBlock_get(void * jarg1) {
  void * jresult ;
  PixelObject *arg1 = 0 ;
  PtrControlBlock *result = 0 ;
  
  arg1 = (PixelObject *)jarg1; 
  result = (PtrControlBlock *) ((arg1)->cBlock);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Module() {
  void * jresult ;
  Module *result = 0 ;
  
  result = (Module *)new Module();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Module(void * jarg1) {
  Module *arg1 = 0 ;
  
  arg1 = (Module *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Module_Awake(void * jarg1) {
  Module *arg1 = 0 ;
  
  arg1 = (Module *)jarg1; 
  (arg1)->Awake();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Module_Start(void * jarg1) {
  Module *arg1 = 0 ;
  
  arg1 = (Module *)jarg1; 
  (arg1)->Start();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Module_Update(void * jarg1) {
  Module *arg1 = 0 ;
  
  arg1 = (Module *)jarg1; 
  (arg1)->Update();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Module_MatrixUpdate(void * jarg1) {
  Module *arg1 = 0 ;
  
  arg1 = (Module *)jarg1; 
  (arg1)->MatrixUpdate();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Module_PhysicsUpdate(void * jarg1) {
  Module *arg1 = 0 ;
  
  arg1 = (Module *)jarg1; 
  (arg1)->PhysicsUpdate();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Module_LastUpdate(void * jarg1) {
  Module *arg1 = 0 ;
  
  arg1 = (Module *)jarg1; 
  (arg1)->LastUpdate();
}


SWIGEXPORT int SWIGSTDCALL CSharp_Module_GetType(void * jarg1) {
  int jresult ;
  Module *arg1 = 0 ;
  MODULE_TYPE result;
  
  arg1 = (Module *)jarg1; 
  result = (MODULE_TYPE)(arg1)->GetType();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Module_GetGameObject(void * jarg1) {
  void * jresult ;
  Module *arg1 = 0 ;
  GameObject *result = 0 ;
  
  arg1 = (Module *)jarg1; 
  result = (GameObject *)(arg1)->GetGameObject();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_GameObject() {
  void * jresult ;
  GameObject *result = 0 ;
  
  result = (GameObject *)new GameObject();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_GameObject(void * jarg1) {
  GameObject *arg1 = 0 ;
  
  arg1 = (GameObject *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GameObject_Destroy(void * jarg1) {
  GameObject *arg1 = 0 ;
  
  arg1 = (GameObject *)jarg1; 
  (arg1)->Destroy();
}


SWIGEXPORT void SWIGSTDCALL CSharp_GameObject_AddModule(void * jarg1, int jarg2) {
  GameObject *arg1 = 0 ;
  MODULE_TYPE arg2 ;
  
  arg1 = (GameObject *)jarg1; 
  arg2 = (MODULE_TYPE)jarg2; 
  (arg1)->AddModule(arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_GameObject_HasModule(void * jarg1, int jarg2) {
  unsigned int jresult ;
  GameObject *arg1 = 0 ;
  MODULE_TYPE arg2 ;
  bool result;
  
  arg1 = (GameObject *)jarg1; 
  arg2 = (MODULE_TYPE)jarg2; 
  result = (bool)(arg1)->HasModule(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_GameObject_GetModule(void * jarg1, int jarg2) {
  void * jresult ;
  GameObject *arg1 = 0 ;
  MODULE_TYPE arg2 ;
  Module *result = 0 ;
  
  arg1 = (GameObject *)jarg1; 
  arg2 = (MODULE_TYPE)jarg2; 
  result = (Module *)(arg1)->GetModule(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_GameObject_GetHash(void * jarg1) {
  unsigned int jresult ;
  GameObject *arg1 = 0 ;
  unsigned long result;
  
  arg1 = (GameObject *)jarg1; 
  result = (unsigned long)(arg1)->GetHash();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GameObject_name_set(void * jarg1, const char * jarg2) {
  GameObject *arg1 = 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = (GameObject *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  if (arg1) (arg1)->name = *arg2;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_GameObject_name_get(void * jarg1) {
  const char * jresult ;
  GameObject *arg1 = 0 ;
  std::string *result = 0 ;
  
  arg1 = (GameObject *)jarg1; 
  result = (std::string *) & ((arg1)->name);
  jresult = SWIG_csharp_string_callback(result->c_str()); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Camera() {
  void * jresult ;
  Camera *result = 0 ;
  
  result = (Camera *)new Camera();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Camera(void * jarg1) {
  Camera *arg1 = 0 ;
  
  arg1 = (Camera *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Camera_Start(void * jarg1) {
  Camera *arg1 = 0 ;
  
  arg1 = (Camera *)jarg1; 
  (arg1)->Start();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Camera_LastUpdate(void * jarg1) {
  Camera *arg1 = 0 ;
  
  arg1 = (Camera *)jarg1; 
  (arg1)->LastUpdate();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Camera_OrthographicProjection(void * jarg1) {
  Camera *arg1 = 0 ;
  
  arg1 = (Camera *)jarg1; 
  (arg1)->OrthographicProjection();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Camera_PerspectiveProjection(void * jarg1) {
  Camera *arg1 = 0 ;
  
  arg1 = (Camera *)jarg1; 
  (arg1)->PerspectiveProjection();
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Camera_SafeCast(void * jarg1) {
  void * jresult ;
  Module *arg1 = 0 ;
  Camera *result = 0 ;
  
  arg1 = (Module *)jarg1; 
  result = (Camera *)Camera_SafeCast(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DebugCamera() {
  void * jresult ;
  DebugCamera *result = 0 ;
  
  result = (DebugCamera *)new DebugCamera();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_DebugCamera(void * jarg1) {
  DebugCamera *arg1 = 0 ;
  
  arg1 = (DebugCamera *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DebugCamera_Start(void * jarg1) {
  DebugCamera *arg1 = 0 ;
  
  arg1 = (DebugCamera *)jarg1; 
  (arg1)->Start();
}


SWIGEXPORT void SWIGSTDCALL CSharp_DebugCamera_Update(void * jarg1) {
  DebugCamera *arg1 = 0 ;
  
  arg1 = (DebugCamera *)jarg1; 
  (arg1)->Update();
}


SWIGEXPORT void SWIGSTDCALL CSharp_DebugCamera_LastUpdate(void * jarg1) {
  DebugCamera *arg1 = 0 ;
  
  arg1 = (DebugCamera *)jarg1; 
  (arg1)->LastUpdate();
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DebugCamera_SafeCast(void * jarg1) {
  void * jresult ;
  Module *arg1 = 0 ;
  DebugCamera *result = 0 ;
  
  arg1 = (Module *)jarg1; 
  result = (DebugCamera *)DebugCamera_SafeCast(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Transform() {
  void * jresult ;
  Transform *result = 0 ;
  
  result = (Transform *)new Transform();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Transform(void * jarg1) {
  Transform *arg1 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_MatrixUpdate(void * jarg1) {
  Transform *arg1 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  (arg1)->MatrixUpdate();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_Start(void * jarg1) {
  Transform *arg1 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  (arg1)->Start();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetPosition__SWIG_0(void * jarg1, void * jarg2) {
  Transform *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return ;
  } 
  (arg1)->SetPosition((PVector3 const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetPosition__SWIG_1(void * jarg1, float jarg2, float jarg3, float jarg4) {
  Transform *arg1 = 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  (arg1)->SetPosition(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetPosition__SWIG_2(void * jarg1, int jarg2, int jarg3, int jarg4) {
  Transform *arg1 = 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  (arg1)->SetPosition(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddPosition__SWIG_0(void * jarg1, void * jarg2) {
  Transform *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return ;
  } 
  (arg1)->AddPosition((PVector3 const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddPosition__SWIG_1(void * jarg1, float jarg2, float jarg3, float jarg4) {
  Transform *arg1 = 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  (arg1)->AddPosition(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddPosition__SWIG_2(void * jarg1, int jarg2, int jarg3, int jarg4) {
  Transform *arg1 = 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  (arg1)->AddPosition(arg2,arg3,arg4);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_GetPosition(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PVector3 *result = 0 ;
  
  arg1 = (Transform *)jarg1; 
  result = (PVector3 *) &(arg1)->GetPosition();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetRotation__SWIG_0(void * jarg1, void * jarg2) {
  Transform *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return ;
  } 
  (arg1)->SetRotation((PVector3 const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetRotation__SWIG_1(void * jarg1, float jarg2, float jarg3, float jarg4) {
  Transform *arg1 = 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  (arg1)->SetRotation(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetRotation__SWIG_2(void * jarg1, int jarg2, int jarg3, int jarg4) {
  Transform *arg1 = 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  (arg1)->SetRotation(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddRotation__SWIG_0(void * jarg1, void * jarg2) {
  Transform *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return ;
  } 
  (arg1)->AddRotation((PVector3 const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddRotation__SWIG_1(void * jarg1, float jarg2, float jarg3, float jarg4) {
  Transform *arg1 = 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  (arg1)->AddRotation(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddRotation__SWIG_2(void * jarg1, int jarg2, int jarg3, int jarg4) {
  Transform *arg1 = 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  (arg1)->AddRotation(arg2,arg3,arg4);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_GetRotation(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PVector3 *result = 0 ;
  
  arg1 = (Transform *)jarg1; 
  result = (PVector3 *) &(arg1)->GetRotation();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetScale__SWIG_0(void * jarg1, void * jarg2) {
  Transform *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return ;
  } 
  (arg1)->SetScale((PVector3 const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetScale__SWIG_1(void * jarg1, float jarg2, float jarg3, float jarg4) {
  Transform *arg1 = 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  (arg1)->SetScale(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_SetScale__SWIG_2(void * jarg1, int jarg2, int jarg3, int jarg4) {
  Transform *arg1 = 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  (arg1)->SetScale(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddScale__SWIG_0(void * jarg1, void * jarg2) {
  Transform *arg1 = 0 ;
  PVector3 *arg2 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (PVector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PVector3 const & is null", 0);
    return ;
  } 
  (arg1)->AddScale((PVector3 const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddScale__SWIG_1(void * jarg1, float jarg2, float jarg3, float jarg4) {
  Transform *arg1 = 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  (arg1)->AddScale(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_AddScale__SWIG_2(void * jarg1, int jarg2, int jarg3, int jarg4) {
  Transform *arg1 = 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  (arg1)->AddScale(arg2,arg3,arg4);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_GetScale(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PVector3 *result = 0 ;
  
  arg1 = (Transform *)jarg1; 
  result = (PVector3 *) &(arg1)->GetScale();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_GetWorldMatrix(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PMatrix *result = 0 ;
  
  arg1 = (Transform *)jarg1; 
  result = (PMatrix *) &(arg1)->GetWorldMatrix();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_GetLookVector(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PVector3 result;
  
  arg1 = (Transform *)jarg1; 
  result = (arg1)->GetLookVector();
  jresult = new PVector3(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_GetRightVector(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PVector3 result;
  
  arg1 = (Transform *)jarg1; 
  result = (arg1)->GetRightVector();
  jresult = new PVector3(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_GetUpVector(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PVector3 result;
  
  arg1 = (Transform *)jarg1; 
  result = (arg1)->GetUpVector();
  jresult = new PVector3(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_GetLocal(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PMatrix result;
  
  arg1 = (Transform *)jarg1; 
  result = (arg1)->GetLocal();
  jresult = new PMatrix(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_World_Matrix_set(void * jarg1, void * jarg2) {
  Transform *arg1 = 0 ;
  PMatrix *arg2 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (PMatrix *)jarg2; 
  if (arg1) (arg1)->World_Matrix = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_World_Matrix_get(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PMatrix *result = 0 ;
  
  arg1 = (Transform *)jarg1; 
  result = (PMatrix *)& ((arg1)->World_Matrix);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_Local_Matrix_set(void * jarg1, void * jarg2) {
  Transform *arg1 = 0 ;
  PMatrix *arg2 = 0 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = (PMatrix *)jarg2; 
  if (arg1) (arg1)->Local_Matrix = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_Local_Matrix_get(void * jarg1) {
  void * jresult ;
  Transform *arg1 = 0 ;
  PMatrix *result = 0 ;
  
  arg1 = (Transform *)jarg1; 
  result = (PMatrix *)& ((arg1)->Local_Matrix);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_IsChange_Postion_set(void * jarg1, unsigned int jarg2) {
  Transform *arg1 = 0 ;
  bool arg2 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->IsChange_Postion = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Transform_IsChange_Postion_get(void * jarg1) {
  unsigned int jresult ;
  Transform *arg1 = 0 ;
  bool result;
  
  arg1 = (Transform *)jarg1; 
  result = (bool) ((arg1)->IsChange_Postion);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_IsChange_Rotation_set(void * jarg1, unsigned int jarg2) {
  Transform *arg1 = 0 ;
  bool arg2 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->IsChange_Rotation = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Transform_IsChange_Rotation_get(void * jarg1) {
  unsigned int jresult ;
  Transform *arg1 = 0 ;
  bool result;
  
  arg1 = (Transform *)jarg1; 
  result = (bool) ((arg1)->IsChange_Rotation);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Transform_IsChange_Scale_set(void * jarg1, unsigned int jarg2) {
  Transform *arg1 = 0 ;
  bool arg2 ;
  
  arg1 = (Transform *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->IsChange_Scale = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Transform_IsChange_Scale_get(void * jarg1) {
  unsigned int jresult ;
  Transform *arg1 = 0 ;
  bool result;
  
  arg1 = (Transform *)jarg1; 
  result = (bool) ((arg1)->IsChange_Scale);
  jresult = result; 
  return jresult;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_Transform_RegisterLua() {
  const char * jresult ;
  std::string result;
  
  result = Transform::RegisterLua();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Transform_SafeCast(void * jarg1) {
  void * jresult ;
  Module *arg1 = 0 ;
  Transform *result = 0 ;
  
  arg1 = (Module *)jarg1; 
  result = (Transform *)Transform_SafeCast(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_LuaScript() {
  void * jresult ;
  LuaScript *result = 0 ;
  
  result = (LuaScript *)new LuaScript();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_LuaScript(void * jarg1) {
  LuaScript *arg1 = 0 ;
  
  arg1 = (LuaScript *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_LuaScript_Awake(void * jarg1) {
  LuaScript *arg1 = 0 ;
  
  arg1 = (LuaScript *)jarg1; 
  (arg1)->Awake();
}


SWIGEXPORT void SWIGSTDCALL CSharp_LuaScript_Start(void * jarg1) {
  LuaScript *arg1 = 0 ;
  
  arg1 = (LuaScript *)jarg1; 
  (arg1)->Start();
}


SWIGEXPORT void SWIGSTDCALL CSharp_LuaScript_Update(void * jarg1) {
  LuaScript *arg1 = 0 ;
  
  arg1 = (LuaScript *)jarg1; 
  (arg1)->Update();
}


SWIGEXPORT void SWIGSTDCALL CSharp_LuaScript_Reload(void * jarg1) {
  LuaScript *arg1 = 0 ;
  
  arg1 = (LuaScript *)jarg1; 
  (arg1)->Reload();
}


SWIGEXPORT void SWIGSTDCALL CSharp_LuaScript_Register(void * jarg1, const char * jarg2) {
  LuaScript *arg1 = 0 ;
  std::string arg2 ;
  
  arg1 = (LuaScript *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  (&arg2)->assign(jarg2); 
  (arg1)->Register(SWIG_STD_MOVE(arg2));
}


SWIGEXPORT void * SWIGSTDCALL CSharp_LuaScript_SafeCast(void * jarg1) {
  void * jresult ;
  Module *arg1 = 0 ;
  LuaScript *result = 0 ;
  
  arg1 = (Module *)jarg1; 
  result = (LuaScript *)LuaScript_SafeCast(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Renderer2D() {
  void * jresult ;
  Renderer2D *result = 0 ;
  
  result = (Renderer2D *)new Renderer2D();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Renderer2D(void * jarg1) {
  Renderer2D *arg1 = 0 ;
  
  arg1 = (Renderer2D *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Renderer2D_LastUpdate(void * jarg1) {
  Renderer2D *arg1 = 0 ;
  
  arg1 = (Renderer2D *)jarg1; 
  (arg1)->LastUpdate();
}


SWIGEXPORT void SWIGSTDCALL CSharp_Renderer2D_SetTexture(void * jarg1, const char * jarg2) {
  Renderer2D *arg1 = 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = (Renderer2D *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  (arg1)->SetTexture((std::string const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Renderer2D_SafeCast(void * jarg1) {
  void * jresult ;
  Module *arg1 = 0 ;
  Renderer2D *result = 0 ;
  
  arg1 = (Module *)jarg1; 
  result = (Renderer2D *)Renderer2D_SafeCast(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT PixelObject * SWIGSTDCALL CSharp_Module_SWIGUpcast(Module *jarg1) {
    return (PixelObject *)jarg1;
}

SWIGEXPORT PixelObject * SWIGSTDCALL CSharp_GameObject_SWIGUpcast(GameObject *jarg1) {
    return (PixelObject *)jarg1;
}

SWIGEXPORT Module * SWIGSTDCALL CSharp_Camera_SWIGUpcast(Camera *jarg1) {
    return (Module *)jarg1;
}

SWIGEXPORT Module * SWIGSTDCALL CSharp_DebugCamera_SWIGUpcast(DebugCamera *jarg1) {
    return (Module *)jarg1;
}

SWIGEXPORT Module * SWIGSTDCALL CSharp_Transform_SWIGUpcast(Transform *jarg1) {
    return (Module *)jarg1;
}

SWIGEXPORT Module * SWIGSTDCALL CSharp_LuaScript_SWIGUpcast(LuaScript *jarg1) {
    return (Module *)jarg1;
}

SWIGEXPORT Module * SWIGSTDCALL CSharp_Renderer2D_SWIGUpcast(Renderer2D *jarg1) {
    return (Module *)jarg1;
}

#ifdef __cplusplus
}
#endif

